### ISSUE TITLE
Youtube video comments cause application close

### ISSUE THREAD

**Issue by ScriptSmith** [ScriptSmith/reaper#2]
Inputting a youtube video-id into youtube function-2 results in an application exit

**Comment by ScriptSmith** [comment]
**Traceback**:
```
ERROR:reaper:Uncaught exception
Traceback (most recent call last):
  File "/home/adam/git/reaper/reaper.py", line 908, in initiate_download
    self.generator_thread = GenerateData(source, generator, count)
  File "/home/adam/git/reaper/reaper.py", line 61, in __init__
    chunk_size = int(count / 1000)
TypeError: unsupported operand type(s) for /: 'QSpinBox' and 'int'
```
Fixed by:
b0440ca
